Prevent MacOSX 10.6 build error disabling OpenCL. Fixes #17
This commit allows the build to succeed and avoid the error
reported below. Since OpenCL is not required by SlicerOpenCV,
it can be disabled.

Error:

//----------------
[...]

#define CV_OclDbgAssert(expr) do { if (isRaiseError()) { CV_Assert(expr); } else { (void)(expr); } } while ((void)0, 0)
                                                                                          ^
/Users/kitware/Dashboards/Experimental/SlicerOpenCV-Release/OpenCV-source/modules/core/src/ocl.cpp:3520:53: error: use of undeclared
      identifier 'CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE'
    return clGetKernelWorkGroupInfo(p->handle, dev, CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE,
                                                    ^
/Users/kitware/Dashboards/Experimental/SlicerOpenCV-Release/OpenCV-source/modules/core/src/ocl.cpp:5004:28: error: use of undeclared
      identifier 'clEnqueueReadBufferRect'
                CV_Assert( clEnqueueReadBufferRect(q, (cl_mem)u->handle, CL_TRUE,
                           ^
/Users/kitware/Dashboards/Experimental/SlicerOpenCV-Release/OpenCV-source/modules/core/include/opencv2/core/base.hpp:410:33: note: expanded
      from macro 'CV_Assert'
#define CV_Assert( expr ) if(!!(expr)) ; else cv::error( cv::Error::StsAssert, #expr, CV_Func, __FILE__, __LINE__ )
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
//----------------